FROM node:alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .

RUN yarn install --production

ENV REACT_APP_SERVER_URL=http://192.168.64.3:9000

RUN yarn build
RUN yarn global add serve

EXPOSE 5000

CMD ["serve", "-s", "build"]
