FROM node:alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .

RUN yarn install --production

# ENV MONGO_URI=mongodb://localhost:27018/tasks
ENV PORT=9000

EXPOSE 9000

CMD ["yarn", "start"]
